services:
  wn1:
    container_name: wn1
    hostname: wn1
    image: retilab/ubuntu-hpc
    environment:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    platform: linux/amd64 # per processori ARM con emulatore Rosetta 2  
    volumes:
      - /Users/federicobecchi/Documents/HPC/lab/01:/root
    ports:
      - 2201:22
              
  wn2:
    container_name: wn2
    hostname: wn2
    image: retilab/ubuntu-hpc
    environment:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    volumes:
      - /Users/federicobecchi/Documents/HPC/lab/01:/root
    platform: linux/amd64 # per processori ARM con emulatore Rosetta 2
    ports:
      - 2202:22